Shortcut-fe: Changes to support kernel upgrade 6.6
ERROR:
sfe_ipv4.c:4569:30: error: call to undeclared function 'register_sysctl_paths'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

note: did you mean 'register_sysctl_sz'?

sysctl.h:233:26: note: 'register_sysctl_sz' declared here

Change-Id: I23e9470d0ce12525437c9d33978ad264b9bd18b2
Signed-off-by: Medha <quic_medhlnu@quicinc.com>